local hm = hexmap

local function pc(t, id, owner, hand, vault)
	return t.actor({ id = id, kind = "pc", name = id, owner = owner or "pl_1",
		ext = { [hm.id] = { traits = { nerve = 1, grace = 2, wit = 0 }, hand = hand or { "dash" }, vault = vault or { "rally", "trick" } } } })
end

local function scene(t)
	t.commit({ t = "scene.add", scene = { id = "s_1", name = "S", map = "", map_path = "", level = "ground", overrides = {}, fog = { enabled = false, explored = {} }, tokens = {} } }, "scene")
end

hm.test("focus turns: the GM starts with the focus and grants it on request", function(t)
	scene(t)
	local a = pc(t, "a_ana")
	t.ok(t.turns_start("s_1", hm.id), "started")
	local turns = hm.turns.current()
	t.eq(turns.strategy, "focus", "focus shape")
	t.eq(turns.focus, "gm", "the GM holds it first")
	t.eq(#turns.order, 0, "no order at all")
	hm.turns.request("pl_1", "actor:a_ana")
	t.eq(#hm.turns.current().requests, 1, "a request is recorded")
	hm.turns.set_focus("actor:a_ana", "gm")
	turns = hm.turns.current()
	t.eq(turns.focus, "actor:a_ana", "granted")
	t.eq(#turns.requests, 0, "the request is cleared")
	t.eq(turns.history[#turns.history], "actor:a_ana", "history remembers")
end)

hm.test("a dark roll feeds the pool and hands the focus to the GM", function(t)
	scene(t)
	local a = pc(t, "a_ana")
	t.turns_start("s_1", hm.id)
	hm.turns.set_focus("actor:a_ana", "gm")
	-- faces typed in: bright 3, dark 9 → dark tone
	local r = t.roll_with_faces({ bright = { 3 }, dark = { 9 } }, { named = { bright = "1d10", dark = "1d10" }, kind = "action" }, { actor = a, kind = "action", dc = 10 })
	t.eq(r.result.outcome, "success_dark", "12 ≥ 10 but the dark die is higher")
	t.eq(r.result.tone, "dark", "tone")
	r = t.roll_with_faces({ bright = { 7 }, dark = { 7 } }, { named = { bright = "1d10", dark = "1d10" }, kind = "action" }, { actor = a, kind = "action", dc = 30 })
	t.eq(r.result.outcome, "shine", "doubles shine whatever the difficulty")
	-- through the action, with the live dice
	local out = t.dispatch("act", { actor = a, trait = "grace", dc = 5 })
	if out.tone == "dark" then
		t.eq(hm.state.get("encounter").pool, 1, "the pool grew")
		t.eq(hm.turns.focus(), "gm", "and the GM took the focus")
	else
		t.eq(hm.turns.focus(), "actor:a_ana", "bright: the player keeps the focus")
	end
end)

hm.test("spotlighting an adversary costs pool; none, no spotlight", function(t)
	scene(t)
	pc(t, "a_ana")
	local g = t.actor({ id = "a_gob", kind = "npc", ext = { [hm.id] = { traits = { nerve = 0 }, adversary = true } } })
	t.turns_start("s_1", hm.id)
	local ok = pcall(function() hm.turns.set_focus("actor:a_gob", "gm") end)
	t.ok(not ok, "with an empty pool the focus_changed hook vetoes")
	t.eq(hm.turns.focus(), "gm", "the focus did not move")
	t.commit(hm.state.set("encounter", "", { pool = 2 }), "pool")
	hm.turns.set_focus("actor:a_gob", "gm")
	t.eq(hm.turns.focus(), "actor:a_gob", "with pool it moves")
	t.eq(hm.state.get("encounter").pool, 1, "and one was spent")
end)

hm.test("cards: play from the hand, recall from the vault for strain", function(t)
	local a = pc(t, "a_ana")
	t.dispatch("setup", { actor = a })
	local out = t.dispatch("play", { actor = a, card = "dash" })
	t.eq(out.effects, 1, "dash grants an effect")
	t.eq(hm.value(hm.derived(a).evade), 12, "8 + grace 2 + quick 2")
	local ok = pcall(function() t.dispatch("play", { actor = a, card = "rally" }) end)
	t.ok(not ok, "rally is in the vault, not the hand")
	out = t.dispatch("recall", { actor = a, card = "rally" })
	t.eq(#out.hand, 2, "rally joined the hand")
	t.eq(hm.resources.get("actor:" .. a, "strain").marked, 2, "recall cost 2 strain")
	ok = pcall(function() t.dispatch("play", { actor = a, card = "trick", target = a }) end)
	t.ok(not ok, "trick is still in the vault")
end)

hm.test("damage by thresholds marks boxes; armour asks the owner", function(t)
	local a = pc(t, "a_ana")
	t.dispatch("setup", { actor = a, armour = 1 })
	local out = t.dispatch("damage", { target = a, amount = 5 }, { { spend = true } })
	t.eq(out.boxes, 1, "major hit (2) minus armour (1)")
	t.eq(hm.resources.get("actor:" .. a, "hp").marked, 1, "one box marked")
	t.eq(hm.resources.get("actor:" .. a, "armour").marked, 1, "the armour box is spent")
	out = t.dispatch("damage", { target = a, amount = 9 }, {})
	t.eq(out.boxes, 3, "severe: three boxes, no armour left to ask about")
	t.eq(hm.resources.get("actor:" .. a, "hp").marked, 4, "four marked")
	out = t.dispatch("damage", { target = a, amount = 9 }, {})
	t.ok(out.down, "the track is full: down")
end)

hm.test("a countdown ticks on dark outcomes and pays the GM when done", function(t)
	scene(t)
	local a = pc(t, "a_ana")
	local id = t.dispatch("countdown", { actor = a, name = "Doom", steps = 2 })
	t.eq(hm.tracks.get(id).value, 2, "starts full")
	t.roll_with_faces({ bright = { 2 }, dark = { 8 } }, { named = { bright = "1d10", dark = "1d10" }, kind = "action" }, { actor = a, kind = "action", dc = 5 })
	t.eq(hm.tracks.get(id).value, 1, "a dark success ticks it")
	t.roll_with_faces({ bright = { 8 }, dark = { 2 } }, { named = { bright = "1d10", dark = "1d10" }, kind = "action" }, { actor = a, kind = "action", dc = 5 })
	t.eq(hm.tracks.get(id).value, 1, "a bright one does not")
	t.roll_with_faces({ bright = { 1 }, dark = { 3 } }, { named = { bright = "1d10", dark = "1d10" }, kind = "action" }, { actor = a, kind = "action", dc = 20 })
	t.eq(hm.tracks.get(id).value, 0, "a dark failure finishes it")
	t.ok(hm.tracks.get(id).done, "done")
	t.eq(hm.state.get("encounter").pool, 2, "track_done paid the GM")
end)

hm.test("a helped roll gathers a contribution before it resolves", function(t)
	scene(t)
	local a = pc(t, "a_ana")
	pc(t, "a_ben", "pl_2", {}, {})
	t.turns_start("s_1", hm.id)
	local out = t.dispatch("act", { actor = a, trait = "nerve", dc = 5, help = { by = "pl_2", expr = "1d6" } })
	t.ok(out.total ~= nil, "resolved")
	t.eq(#hm.dice.pending(), 0, "nothing left open")
end)

hm.test("rest: strain clears, the GM gains one", function(t)
	local a = pc(t, "a_ana")
	t.dispatch("setup", { actor = a })
	t.commit(hm.resources.mark("actor:" .. a, "strain", 3), "strain")
	hm.rest("rest")
	t.eq(hm.resources.get("actor:" .. a, "strain").marked, 0, "cleared")
	t.eq(hm.state.get("encounter").pool, 1, "the GM gained one")
	t.eq(hm.clock.get().rests, 1, "the clock counted it")
end)
