-- The plugin's own tests: run with `./run.sh plugintest tests/plugins/sample.ordered`
-- and by the app's self-test. Each runs on a fresh scratch encounter.
local hm = hexmap

local function hero(t, agi, str, armour)
	return t.actor({ id = "a_hero", kind = "pc", name = "Hero", owner = "pl_1",
		ext = { [hm.id] = { level = 2, stats = { agi = agi or 3, str = str or 1, wit = 0 }, armour = armour or 0 } } })
end

hm.test("derive: defence is 10 + agility + armour, typed", function(t)
	local id = hero(t, 3, 1, 2)
	local d = hm.derived(id)
	t.eq(d.defence.total, 15, "defence")
	t.eq(#d.defence.parts, 3, "three parts")
	t.eq(d.defence.parts[2].label, "agility", "the agility part is named")
	t.eq(d.hp_max, 6 + 2 * 4 + 1, "hp_max")
	t.eq(d.label, "Level 2", "a label")
end)

hm.test("schema: bad actor data is refused", function(t)
	local ok = pcall(function()
		t.actor({ id = "a_bad", ext = { [hm.id] = { level = 0, stats = { agi = 1, str = 1, wit = 1 } } } })
	end)
	t.ok(not ok, "level 0 is refused by the schema")
end)

hm.test("conditions change the numbers and stack as declared", function(t)
	local id = hero(t)
	t.dispatch("condition", { key = "shaken", target = "actor:" .. id, value = 1 })
	t.eq(hm.derived(id).defence.total, 11, "shaken lowers the defence")
	t.dispatch("condition", { key = "shaken", target = "actor:" .. id, value = 1 })
	t.eq(#hm.effects.on("actor:" .. id, "shaken"), 1, "highest: no second shaken")
	t.dispatch("condition", { key = "prone", target = "actor:" .. id })
	-- both penalties are "status": under this ruleset's policy the worst one counts, not the sum
	t.eq(hm.derived(id).defence.total, 11, "prone and shaken are both status: only the worst counts")
	t.eq(#hm.derived(id).defence.parts, 5, "but both show in the breakdown")
	t.eq(hm.derived(id).speed, 3, "prone halves speed")
end)

hm.test("rolls go through the hooks", function(t)
	local id = hero(t, 3, 2)
	local r = t.roll_with_faces({ main = { 15 } }, "1d20", { actor = id, kind = "attack", dc = 16 })
	t.eq(r.result.total, 17, "15 + strength 2")
	t.eq(r.result.outcome, "success", "at or above the difficulty")
	t.dispatch("condition", { key = "shaken", target = "actor:" .. id })
	r = t.roll_with_faces({ main = { 15 } }, "1d20", { actor = id, kind = "attack", dc = 16 })
	t.eq(r.result.total, 15, "shaken: -2")
	t.eq(r.result.outcome, "failure", "and now a miss")
	r = t.roll_with_faces({ main = { 20 } }, "1d20", { actor = id, kind = "attack", dc = 30 })
	t.eq(r.result.outcome, "critical", "a natural 20 is a critical whatever the difficulty")
end)

hm.test("strike: a hit spends the target's hit points, armour asks first", function(t)
	local a = hero(t, 3, 2)
	local b = t.actor({ id = "a_gob", kind = "npc", name = "Goblin", owner = "pl_2",
		ext = { [hm.id] = { level = 1, stats = { agi = 0, str = 0, wit = 0 }, armour = 1 } } })
	t.dispatch("setup", { actor = a })
	t.dispatch("setup", { actor = b })
	t.eq(hm.resources.get("actor:" .. b, "hp").current, 10, "goblin starts at 10")
	-- the dice stream is seeded (7); whatever it gives, the bookkeeping must hold
	local out = t.dispatch("strike", { actor = a, target = b }, { { spend = true } })
	local hp = hm.resources.get("actor:" .. b, "hp").current
	if out.outcome == "failure" then
		t.eq(hp, 10, "a miss leaves it whole")
	else
		t.eq(hp, math.max(0, 10 - out.damage), "a hit took the damage")
		t.eq(hm.resources.get("actor:" .. b, "armour").marked, 1, "the armour slot was spent")
	end
end)

hm.test("rest refills and logs", function(t)
	local a = hero(t)
	t.dispatch("setup", { actor = a })
	t.commit(hm.resources.spend("actor:" .. a, "hp", 5), "hurt")
	t.eq(hm.resources.get("actor:" .. a, "hp").current, 10, "hurt")
	local out = t.dispatch("rest", {})
	t.eq(hm.resources.get("actor:" .. a, "hp").current, 15, "rested")
	t.ok(out.refilled >= 1, "something refilled")
end)

hm.test("state: the ruleset keeps encounter-scoped data", function(t)
	t.commit(hm.state.set("encounter", "", { doom = 3 }), "doom")
	t.eq(hm.state.get("encounter").doom, 3, "read back")
end)

hm.test("targets picked on the map: a shove pushes a token, oil splashes an area", function(t)
	local a = t.actor({ id = "a_hero", ext = { [hm.id] = { level = 1, stats = { agi = 2, str = 1, wit = 0 } } } })
	local b = t.actor({ id = "a_gob", ext = { [hm.id] = { level = 1, stats = { agi = 1, str = 0, wit = 0 } } } })
	local c = t.actor({ id = "a_gob2", ext = { [hm.id] = { level = 1, stats = { agi = 1, str = 0, wit = 0 } } } })
	local sc = t.scene(nil, { { id = "t_hero", actor = "a_hero", x = 6, y = 7 }, { id = "t_gob", actor = "a_gob", x = 7, y = 7 }, { id = "t_gob2", actor = "a_gob2", x = 9, y = 7 } })
	t.eq(hm.token("token:t_gob").scene, sc, "hm.token takes a token: ref and says which scene")
	local before = hm.map.token(sc, "t_gob").pos
	local r = t.dispatch("shove", { actor = "a_hero", scene = sc, target = "token:t_gob" })
	t.eq(r.shoved, "t_gob", "shoved")
	t.eq(r.cells, 1, "one cell")
	t.ok(hm.map.token(sc, "t_gob").pos[1] > before[1], "pushed away from the hero")
	local ok, why = pcall(t.dispatch, "shove", { actor = "a_hero", scene = sc, target = "token:t_gob2" })
	t.ok(not ok and tostring(why):find("too far") ~= nil, "too far to shove: " .. tostring(why))
	-- an area target as the host hands it in: the template spec with its origin
	local oil = t.dispatch("throw_oil", { actor = "a_hero", scene = sc, target = { shape = "circle", radius = 1, at = hm.map.token(sc, "t_gob2").pos, direction = 0 } })
	t.ok(oil.cells >= 7, "the splash covers cells: " .. tostring(oil.cells))
	t.eq(#oil.hit, 2, "the goblin under it and the one shoved beside it")
	t.ok(hm.effects.has("actor:a_gob2", "oily"), "and it is oily")
	t.ok(hm.effects.has("actor:a_gob", "oily"), "both are oily")
	t.eq(hm.value(hm.derived("a_gob2").defence), hm.value(hm.derived("a_hero").defence) - 2, "at -1 defence (and one less agility than the hero)")
end)

hm.test("a volley asks every player at once; a dare waits for nobody", function(t)
	t.actor({ id = "a_p1", owner = "pl_1", ext = { [hm.id] = { level = 1, stats = { agi = 1, str = 0, wit = 0 } } } })
	t.actor({ id = "a_p2", owner = "pl_2", ext = { [hm.id] = { level = 1, stats = { agi = 1, str = 0, wit = 0 } } } })
	t.actor({ id = "a_p2b", owner = "pl_2", ext = { [hm.id] = { level = 1, stats = { agi = 1, str = 0, wit = 0 } } } })
	t.actor({ id = "a_npc", ext = { [hm.id] = { level = 1, stats = { agi = 1, str = 0, wit = 0 } } } })
	-- prompt_all: one yield, one answer table with every player's answer
	local r = t.dispatch("volley", {}, { { pl_1 = { dodge = true }, pl_2 = { dodge = false } } })
	t.eq(r.asked, 2, "two players asked (the npc has no owner)")
	t.eq(#r.dodged, 1, "one dodged")
	t.eq(r.dodged[1], "a_p1", "pl_1's")
	t.eq(#r.shaken, 2, "pl_2's two are shaken")
	t.ok(hm.effects.has("actor:a_p2", "shaken") and hm.effects.has("actor:a_p2b", "shaken") and not hm.effects.has("actor:a_p1", "shaken"), "effects follow the answers")
	-- prompt_open: the action returns at once; the hook applies the answer
	local d = t.dispatch("dare", { target = "a_p1", stake = 2 })
	t.ok(d.prompt ~= nil and d.prompt ~= "", "a prompt id came back at once")
	local open = t.prompts()
	t.eq(#open, 1, "the prompt is open")
	t.eq(open[1].to, "pl_1", "for the character's owner")
	t.ok(t.answer(d.prompt, { take = true }, "pl_1"), "pl_1 answers")
	t.eq(#t.prompts(), 0, "closed")
	local b = hm.effects.on("actor:a_p1", "blessed")
	t.eq(#b, 1, "the hook blessed the darer")
	t.eq(b[1].value, 2, "for the stake")
	-- the wrong player may not answer; the deadline answers with the default
	local d2 = t.dispatch("dare", { target = "a_p2" })
	local ok = pcall(t.answer, d2.prompt, { take = true }, "pl_1")
	t.ok(not ok, "pl_1 may not answer pl_2's prompt")
	t.tick(61)
	t.eq(#t.prompts(), 0, "the deadline closed it")
	t.ok(not hm.effects.has("actor:a_p2", "blessed"), "no blessing on silence")
	t.eq(hm.effects.on("actor:a_p2", "shaken")[1].value, 1, "shaken from the volley stays at 1: the timed-out dare added nothing")
end)

hm.test("the order from Lua: reorder, insert, remove, a group of goblins", function(t)
	t.actor({ id = "a_h", ext = { [hm.id] = { level = 1, stats = { agi = 3, str = 0, wit = 0 } } } })
	t.actor({ id = "a_g1", ext = { [hm.id] = { level = 1, stats = { agi = 1, str = 0, wit = 0 } } } })
	t.actor({ id = "a_g2", ext = { [hm.id] = { level = 1, stats = { agi = 0, str = 0, wit = 0 } } } })
	local sc = t.scene(nil, { { id = "t_h", actor = "a_h", x = 3, y = 3 }, { id = "t_g1", actor = "a_g1", x = 5, y = 3 }, { id = "t_g2", actor = "a_g2", x = 6, y = 3 } })
	t.ok(hm.turns.start(sc), "started")
	local o = hm.turns.current().order
	t.eq(o[1] .. o[2] .. o[3], "t_ht_g1t_g2", "highest initiative first")
	t.ok(hm.turns.group("gobs", { "t_g1", "t_g2" }, "Goblins"), "grouped")
	o = hm.turns.current().order
	t.eq(#o, 2, "two slots")
	t.eq(o[2], "group:gobs", "the group is the second")
	t.ok(hm.turns.reorder({ "group:gobs", "t_h" }), "the goblins go first (a delay)")
	t.eq(hm.turns.current().order[1], "group:gobs", "reordered")
	t.ok(hm.turns.remove("t_h"), "the hero leaves the order")
	t.eq(#hm.turns.current().order, 1, "one slot")
	t.ok(hm.turns.insert("t_h", 0), "and comes back at the front")
	t.eq(hm.turns.current().order[1], "t_h", "inserted")
	t.ok(hm.turns.ungroup("gobs"), "ungrouped")
	t.eq(#hm.turns.current().order, 3, "three again")
	local ok = pcall(hm.turns.ungroup, "gobs")
	t.ok(not ok, "no such group is an error")
end)
