local hm = hexmap

local function hero(t, extra)
	local ext = { level = 3, stats = { might = 3, agility = 1, mind = 0 }, ranks = { perception = 1, stealth = 0, athletics = 2 }, ac_base = 14 }
	for k, v in pairs(extra or {}) do ext[k] = v end
	return t.actor({ id = "a_hero", kind = "pc", name = "Hero", owner = "pl_1", ext = { [hm.id] = ext } })
end

hm.test("derive: proficiency is rank × 2 + level, typed", function(t)
	local id = hero(t)
	local d = hm.derived(id)
	t.eq(d.perception.total, 5, "0 + (1*2+3)")
	t.eq(d.athletics.total, 3 + 7, "might 3 + rank 2 → 7")
	t.eq(d.stealth.total, 1, "untrained: no proficiency")
	t.eq(d.ac.total, 15, "ac")
end)

hm.test("four degrees with the natural 20 and 1 steps", function(t)
	local id = hero(t)
	local function roll(face, dc) return t.roll_with_faces({ main = { face } }, "1d20", { actor = id, kind = "check", dc = dc }).result end
	t.eq(roll(15, 10).outcome, "success", "15 vs 10")
	t.eq(roll(19, 9).outcome, "critical_success", "10 above")
	t.eq(roll(5, 10).outcome, "failure", "5 vs 10")
	t.eq(roll(3, 15).outcome, "critical_failure", "more than 10 below")
	t.eq(roll(20, 25).outcome, "success", "a natural 20 lifts a failure to a success")
	t.eq(roll(1, 1).outcome, "failure", "a natural 1 drops a success to a failure")
	t.eq(roll(1, 12).outcome, "critical_failure", "a natural 1 drops a failure to a critical failure")
end)

hm.test("frightened subtracts its value and ticks down at the end of the turn", function(t)
	local id = hero(t)
	t.commit({ t = "scene.add", scene = { id = "s_1", name = "S", map = "", map_path = "", level = "ground", overrides = {}, fog = { enabled = false, explored = {} },
		tokens = { { id = "t_h", name = "Hero", label = "H", art = "", color = "#fff", pos = { 0, 0 }, size = 1, rot = 0, elevation = 0, hidden = false, vision = { radius = 6 }, tags = {}, actor = id } } } }, "scene")
	t.dispatch("condition", { target = id, key = "frightened", value = 2 })
	local r = t.roll_with_faces({ main = { 12 } }, "1d20", { actor = id, kind = "check", dc = 10 })
	t.eq(r.result.total, 10, "12 − 2")
	t.turns_start("s_1", hm.id)
	hm.turns.next()   -- the hero's turn ends (there is only one participant: it wraps)
	local fx = hm.effects.on("actor:" .. id, "frightened")
	t.eq(#fx, 1, "still frightened")
	t.eq(fx[1].value, 1, "but by one less")
	hm.turns.next()
	t.eq(#hm.effects.on("actor:" .. id, "frightened"), 0, "and gone the turn after")
end)

hm.test("the multiple-attack penalty mounts within a turn", function(t)
	local a = hero(t)
	local b = t.actor({ id = "a_gob", kind = "npc", name = "Gob", ext = { [hm.id] = { level = 1, stats = { might = 0, agility = 0, mind = 0 }, ac_base = 10 } } })
	t.dispatch("setup", { actor = b })
	local function attack(face) return t.roll_with_faces({ main = { face } }, "1d20", { actor = a, kind = "attack", dc = 10 }).result end
	t.eq(attack(10).total, 10 + 3 + 5, "first attack: might 3 + proficiency 5")
	t.commit(hm.state.set("encounter", "", { ["attacks/" .. a] = 1 }), "one made")
	t.eq(attack(10).total, 18 - 5, "second: −5")
	t.commit(hm.state.set("encounter", "", { ["attacks/" .. a] = 2 }), "two made")
	t.eq(attack(10).total, 18 - 10, "third: −10")
	t.commit(hm.state.set("encounter", "", { ["attacks/" .. a] = 0 }), "reset")
	local out = t.dispatch("strike", { actor = a, target = b })
	t.ok(out.degree ~= nil, "a strike through the action")
	t.eq((hm.state.get("encounter").attacks or {})[a], 1, "the count went up")
end)

hm.test("compendium: query the shipped pack, spawn a creature, homebrew behaves the same", function(t)
	t.eq(hm.comp.count("creatures"), 6, "six shipped creatures")
	local r = hm.comp.query("creatures", { filter = { kind = "humanoid" }, sort = "-level" })
	t.eq(r.total, 2, "two humanoids")
	t.eq(r.entries[1].id, "goblin-chief", "sorted by level, descending")
	r = hm.comp.query("creatures", { text = "marsh" })
	t.eq(r.total, 1, "full text finds the wisp")
	r = hm.comp.query("creatures", { facets = { "kind" } })
	t.eq(r.facets.kind.humanoid, 2, "facet counts")
	t.commit({ t = "scene.add", scene = { id = "s_1", name = "S", map = "", map_path = "", level = "ground", overrides = {}, fog = { enabled = false, explored = {} }, tokens = {} } }, "scene")
	local out = t.dispatch("spawn", { entry = hm.comp.get("creatures", "wolf"), scene = "s_1" })
	local wolf = hm.actor(out.actor)
	t.eq(wolf.name, "Wolf", "spawned from the entry")
	t.eq(hm.derived(out.actor).ac.total, 14, "with derived numbers")
	t.eq(#hm.tokens(out.actor), 1, "and a token on the scene")
	t.eq(hm.resources.get("actor:" .. out.actor, "hp").max, 12, "and hit points")
	-- a homebrew creature with the wolf's numbers derives the same
	hm.comp.put("creatures", { id = "dire-wolf", name = "Dire wolf", level = 1, kind = "animal", traits = { "animal" }, stats = { might = 2, agility = 2, mind = -2 }, ranks = { perception = 2, stealth = 1, athletics = 2 }, ac_base = 12, hp = 12 })
	t.eq(hm.comp.get("creatures", "dire-wolf").__pack, hm.id .. ".homebrew", "in the homebrew pack")
	local out2 = t.dispatch("spawn", { entry = hm.comp.get("creatures", "dire-wolf"), scene = "s_1" })
	local d1, d2 = hm.derived(out.actor), hm.derived(out2.actor)
	t.eq(d2.ac.total, d1.ac.total, "same ac")
	t.eq(d2.perception.total, d1.perception.total, "same perception")
	t.eq(d2.hp_max, d1.hp_max, "same hp")
	local ok = pcall(function() hm.comp.put("creatures", { id = "bad", name = "Bad", level = 99, stats = { might = 0, agility = 0, mind = 0 } }) end)
	t.ok(not ok, "a homebrew entry that breaks the schema is refused")
end)


hm.test("map: cover raises the difficulty, a burst hits an area, a fire zone burns those who enter", function(t)
	local a = hero(t)
	local b = t.actor({ id = "a_gob", kind = "npc", name = "Gob", ext = { [hm.id] = { level = 1, stats = { might = 0, agility = 0, mind = 0 }, ac_base = 10 } } })
	local c = t.actor({ id = "a_gob2", kind = "npc", name = "Gob 2", ext = { [hm.id] = { level = 1, stats = { might = 0, agility = 0, mind = 0 }, ac_base = 10 } } })
	-- the chapel: a hero at the west door, goblins inside
	local scene = t.scene(nil, { { id = "t_h", actor = a, x = 3, y = 7 }, { id = "t_g", actor = b, x = 9, y = 7 }, { id = "t_g2", actor = c, x = 10, y = 7 } })
	t.dispatch("setup", { actor = b })
	t.dispatch("setup", { actor = c })
	local d = hm.map.distance(scene, "token:t_h", "token:t_g")
	t.ok(d.cells >= 5, "the goblin is some hexes away: " .. tostring(d.cells))
	local los = hm.map.los(scene, "token:t_h", "token:t_g")
	t.ok(los.cover == "none" or los.cover == "partial" or los.cover == "total", "line of sight answers: " .. los.cover)
	-- a burst around the first goblin catches the second next to it: each saves
	local out = t.dispatch("burst", { actor = a, scene = scene, at = "token:t_g", radius = 1, dc = 30 })
	t.ok(out.cells >= 3, "a burst covers several cells: " .. tostring(out.cells))
	t.eq(#out.hit, 2, "both goblins were in it")
	t.ok(out.hit[1].outcome == "failure" or out.hit[1].outcome == "critical_failure", "against dc 30 the save fails: " .. tostring(out.hit[1].outcome))
	t.ok(hm.resources.get("actor:" .. b, "hp").current < 10, "and they took damage")
	-- a fire zone; a goblin walking into it burns
	local fz = t.dispatch("fire_zone", { actor = a, scene = scene, at = "5,6", radius = 1 })
	t.ok(fz.cells >= 3, "the zone has cells")
	t.eq(#hm.map.regions_at(scene, "5,6"), 1, "the region is on the scene")
	local hp_before = hm.resources.get("actor:" .. c, "hp").current
	local mv = hm.map.move(scene, "t_g2", { x = hm.map.token(scene, "t_g2").pos[1], y = hm.map.token(scene, "t_g2").pos[2] })
	t.eq(#mv.entered, 0, "staying put enters nothing")
end)

hm.test("improvise: a creature from the benchmark, a ruling in the log, campaign state", function(t)
	local made = hm.improv and true
	t.ok(made, "hm.improv exists")
	-- the benchmark makes valid actor data at any level
	local a = hero(t)
	local scene = t.scene(nil, { { id = "t_h", actor = a, x = 3, y = 7 } })
	local id = t.improvise("creature", { level = 4, role = "brute" }, scene, "5,7")
	local brute = hm.actor(id)
	t.eq(brute.ext[hm.id].level, 4, "level 4")
	t.eq(brute.ext[hm.id].stats.might, 3, "a brute's might grows with level")
	t.eq(hm.resources.get("actor:" .. id, "hp").max, 48, "8 + 4 × 10 hp")
	t.ok(#hm.tokens(id) == 1, "and it stands on the scene")
	-- a ruling, with the rule it rests on
	local r = t.dispatch("rule", { text = "Cover from a table is partial", rule = "cover", tags = { "cover", "terrain" } })
	t.ok(type(r.id) == "string" and r.id ~= "", "the ruling has an id")
	-- campaign-scoped state survives in the encounter's campaign block
	t.commit(hm.state.set("campaign", "", { visits = (hm.state.get("campaign").visits or 0) + 1 }), "Visit")
	t.eq(hm.state.get("campaign").visits, 1, "campaign state reads back")
	t.ok(type(hm.campaign().session) == "number", "the session number is known")
	-- a checkpoint and a restore
	local cp = hm.checkpoint.mark("before the fight")
	t.commit(hm.resources.spend("actor:" .. id, "hp", 10), "Hurt")
	t.eq(hm.resources.get("actor:" .. id, "hp").current, 38, "hurt")
	hm.checkpoint.restore(cp)
	t.eq(hm.resources.get("actor:" .. id, "hp").current, 48, "whole again after the restore")
end)
